# Encoding: utf-8

# --
# Copyright (c) 2008-2018 Net-ng.
# All rights reserved.
#
# This software is licensed under the BSD License, as described in
# the file LICENSE.txt, which you should have received as part of
# this distribution.
# --

image: docker-registry.net-ng.com/nng/dind-ubuntu:7

tests2:
  script:
    - /opt/stackless/bin/pip2 install flake8 pytest .
    - /opt/stackless/bin/flake8 nagare
    - /opt/stackless/bin/pytest

tests3:
  script:
  - /opt/stackless/bin/pip3 install flake8 pytest .
  - /opt/stackless/bin/flake8 nagare
  - /opt/stackless/bin/pytest
